USE [Celestica_pre_test]
GO

/****** Object:  View [dbo].[TBL_VIEW_PROMOTION]    Script Date: 6/25/2025 10:59:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TBL_VIEW_PROMOTION]
AS
SELECT        dbo.TBL_MST_PROMOTION.PROMOTION_NAME, dbo.TBL_MST_PROMOTION.PROMOTION_DESCRIPTION, dbo.TBL_MST_PROMOTION.PROMOTION_PRICE, dbo.TBL_MST_PROMOTION.START_DATE, 
                         dbo.TBL_MST_PROMOTION.END_DATE, dbo.TBL_MST_PROMOTION.REMAINS, dbo.TBL_MST_PROMOTION.MIN_RANK, dbo.TBL_MST_CUSTOMER.CUSTOMER_CODE, dbo.TBL_MST_CUSTOMER.CUSTOMER_NAME, 
                         dbo.TBL_MST_CUSTOMER.CUSTOMER_LAST_NAME, dbo.TBL_MST_CUSTOMER.CUSTOMER_EMAIL, dbo.TBL_MST_CUSTOMER.RACK_LEVEL, dbo.TBL_PROC_POMOTION.REDEEM_DATE, 
                         dbo.TBL_PROC_POMOTION.STATUS, dbo.TBL_MST_MEMBER_RANK.RACK_NAME
FROM            dbo.TBL_MST_CUSTOMER INNER JOIN
                         dbo.TBL_MST_MEMBER_RANK ON dbo.TBL_MST_CUSTOMER.RACK_LEVEL = dbo.TBL_MST_MEMBER_RANK.RACK_LEVEL INNER JOIN
                         dbo.TBL_PROC_POMOTION ON dbo.TBL_MST_CUSTOMER.ID = dbo.TBL_PROC_POMOTION.CUSTOMER_ID INNER JOIN
                         dbo.TBL_MST_PROMOTION ON dbo.TBL_PROC_POMOTION.PROMOTION_ID = dbo.TBL_MST_PROMOTION.ID
GO 
 
