USE [Celestica_pre_test]
GO

/****** Object:  Table [dbo].[TBL_MST_MEMBER_RANK]    Script Date: 6/25/2025 10:58:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_MST_MEMBER_RANK](
	[RACK_LEVEL] [int] NOT NULL,
	[RACK_NAME] [nvarchar](50) NOT NULL,
	[CREATED_BY] [nvarchar](200) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](200) NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_TBL_MST_MEMBER_RANK] PRIMARY KEY CLUSTERED 
(
	[RACK_LEVEL] ASC,
	[RACK_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


