USE [Celestica_pre_test]
GO

/****** Object:  Table [dbo].[TBL_MST_CUSTOMER]    Script Date: 6/25/2025 10:57:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_MST_CUSTOMER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](10) NULL,
	[CUSTOMER_NAME] [nvarchar](200) NULL,
	[CUSTOMER_LAST_NAME] [nvarchar](200) NULL,
	[BIRTH_DATE] [date] NULL,
	[CUSTOMER_EMAIL] [nvarchar](200) NULL,
	[EXP_DATE] [date] NULL,
	[STATUS] [char](1) NULL,
	[RACK_LEVEL] [int] NULL,
	[CREATED_BY] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[UPDATED_BY] [nvarchar](50) NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_TBL_CUSTOMER_MASTER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


