# Stage 1: Build Angular App
FROM node:18.19.0-alpine3.18 AS build


WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve with NGINX
FROM nginx:1.23.0-alpine

# ✅ Add nginx.conf for Cloud Run
COPY default.conf /etc/nginx/conf.d/default.conf

# ✅ Copy built app
COPY --from=build /app/dist/celestica_pre_test /usr/share/nginx/html

EXPOSE 8080
