# Stage 1: Build
FROM node:18.19.0-alpine3.18 as build

WORKDIR /app

# Copy package files and install dependencies
COPY ./package*.json ./
RUN npm ci

# Copy source files and build
COPY ./ ./
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:1.23.0-alpine

# Expose port
EXPOSE 8080

# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Copy built app from previous stage
COPY --from=build /app/dist/ngcloudrundemo /usr/share/nginx/html
