# Stage 1: Build Angular App
FROM node:18.19.0-alpine3.18 as build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve with NGINX
FROM nginx:1.23.0-alpine

# ✅ Add nginx.conf for Cloud Run
COPY nginx.conf /etc/nginx/nginx.conf

# ✅ Copy built app
COPY --from=build /app/dist/ngcloudrundemo /usr/share/nginx/html

EXPOSE 8080
